### ISSUE TITLE
Use DotEnv variable for base url

### ISSUE THREAD

**Issue by vikashjajra** [vinsdragonis/Project-Nexus#112]
### Problem
So I was recently working on the upvote system which required me to make changes to the API part of the project. I was required to work on a local copy of DB so I accidentally don't make project-breaking changes to the actual DB. However, at that time I realized that the base URL is hardcoded in the client-side code. Thus I had to go and make changes at every instance of the URL and I will have to revert the URL to make a PR.

### Possible Solution
Use a DotEnv variable for the base URL, thus we only have to make changes in the dotenv file. Not only that, it will ensure we don't forget to change the URL at any place before merging any PR.

**Comment by vinsdragonis** [comment]
I did experiment with that during the early stages of development. Due to the app not recognizing it, I had to switch to using the complete URL in every possible place.
As much as using a dotenv variable seems efficient, I am unsure if it would work since I ran into that issue. But you're welcome to try if you can get it to work.

**Comment by vikashjajra** [comment]
Have made some changes and it seems to work fine. I have opened a PR at #113
